FROM python:3.11-slim

WORKDIR /app

COPY ./notification_manager/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY notification_manager/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
