FROM python:3.11-alpine

WORKDIR /app

COPY ./notification_manager/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY notification_manager/consumer/ .

CMD ["python", "receiver.py"]

