name: Docker Compose Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create external Docker networks
        run: |
          docker network create service_email_network || true
          
      - name: Build and start containers
        working-directory: docker
        run: |  
          echo "Current working directory:"
          pwd
          docker-compose up -d --build

      - name: Wait for services to start
        run: |
          echo "Waiting for services to become healthy..."
          sleep 20
          echo "Logs from docker_email_service_1:"
          docker logs docker_email_service_1

          echo "Logs from docker_consumer_1:"
          docker logs docker_consumer_1

          echo "Logs from docker_rabbitmq_1:"
          docker logs docker_rabbitmq_1

          echo "Docker ps -a:"
          docker ps -a

      - name: Check if API Gateway is running
        run: |
          curl --fail http://localhost:9000 || (echo "Email notification not responding" && exit 1)

      - name: Tear down containers and networks
        if: always()
        working-directory: docker
        run: |
          docker-compose down -v
          docker network rm service_employee_network || true
